//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektPlanung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Benutzer
    {
        public int ben_ID { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public string Mail { get; set; }
        public string Passwort { get; set; }
        public System.Guid AktivierungsCode { get; set; }
        public bool istBestaetigt { get; set; }
    }
}
